# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:22-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

CMD ["node", "/app/dist/index.js"]
